# Navigation Links
#   默认语言（简体中文）要链接到主页的某个部分，请使用井号（#）后跟该部分的ID。
#   weight 参数定义了链接的显示顺序。

main:
  - name: 项目
    url: /#projects
    weight: 10
  - name: 技能
    url: /#skills
    weight: 20
  - name: 经历
    url: /#experience
    weight: 30
  - name: 博客
    url: /#blog
    weight: 40
  - name: 联系
    url: /#contact
    weight: 50

# main:
#   - name: Projects
#     url: /#projects
#     weight: 10
#   - name: Skills
#     url: /#skills
#     weight: 20
#   - name: Experience
#     url: /#experience
#     weight: 30
#   - name: Blog
#     url: /#blog
#     weight: 40
#   - name: Contact
#     url: /#contact
#     weight: 50
